name: Generate GitHub animations

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_snake:
    name: Generate Snake Animation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: marcoscode404
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          destination_dir: snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate_pacman:
    name: Generate Pacman Animation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
  
      - name: Create dist directory
        run: mkdir -p dist
  
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          user: marcoscode404
  
      - name: Debug - Show files after generation
        run: |
          echo "Conteúdo da pasta atual:"
          ls -R
  
      - name: Find and move pacman-contribution-graph.svg
        run: |
          FILE=$(find . -name pacman-contribution-graph.svg)
          echo "Encontrado em: $FILE"
          mv "$FILE" dist/
  
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          destination_dir: pacman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
