name: Generate pacman animation

on:
  schedule:
    - cron: "15 */12 * * *"  # roda 15 minutos depois da cobrinha
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate pacman contribution graph
        uses: ldelossa/pacman-contribution-graph@v1.0.0
        with:
          user: marcoscode404
          output_path: dist/
          dark: true

      - name: Push pacman SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
