name: Generate Pacman Animation

on:
  schedule:
    - cron: '5 */12 * * *'  # A cada 12h, 5 min depois do Snake
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_pacman:
    name: Generate Pacman Animation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          user: marcoscode404

      - name: Debug - Mostrar onde foi salvo
        run: |
          echo "Arquivos encontrados:"
          find . -name pacman-contribution-graph.svg

      # ❌ Esta etapa foi removida (era desnecessária e causava erro)
      # - name: Move pacman-contribution-graph.svg to dist
      #   run: mv ./pacman-contribution-graph.svg dist/

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          destination_dir: pacman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
